// The packager. bundleToSingleHtml does the hard part; this adds only what
// lives downstream of the frame and then asserts the result is self-contained.
//
// The handover point matters: everything before bundleToSingleHtml was validated
// by `hyperframes check` against the source project. Everything this file adds
// after it — fonts, chrome, CSP, the notice — is covered ONLY by gate 2. Any
// future addition here must land there or it is untested.
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { bundleToSingleHtml } from '@hyperframes/core/compiler';
import { declarationFor, drift } from './tokens.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const jsSafe = (s) => s.replace(/<\/script/gi, '<\\/script');

// data: is required twice over and both omissions fail silently:
//   connect-src  the runtime fetches the LUT the bundler just inlined as a data URI
//   script-src   the AudioWorklet FX modules are data: URLs
const CSP = [
  "default-src 'none'",
  "script-src 'unsafe-inline' data:",
  "style-src 'unsafe-inline'",
  'img-src data:',
  'media-src data:',
  'font-src data:',
  'connect-src data:',
  "base-uri 'none'",
  "form-action 'none'",
  "frame-src 'none'",
  "object-src 'none'",
].join('; ');

export async function build(brand, slug) {
  // One stray CI variable silently converts a self-contained artifact into a
  // CDN-dependent one: HYPERFRAME_RUNTIME_URL takes precedence over
  // runtime:'inline' and emits a <script src> instead.
  if (process.env.HYPERFRAME_RUNTIME_URL) {
    throw new Error('HYPERFRAME_RUNTIME_URL is set. It overrides runtime:"inline" and emits a <script src>, which would ship a CDN-dependent artifact. Unset it.');
  }

  const film = path.join(ROOT, 'work', brand, slug);
  const src = fs.readFileSync(path.join(film, 'index.html'), 'utf8');
  const { pack, decl } = await declarationFor(brand);
  const packDir = path.join(ROOT, 'brands', brand);

  // The values that SHIP are the film's own declared defaults — the bundler
  // takes no variables option. So the film's declaration is the brand's, and
  // drift between them is a brand violation that nothing else would catch.
  const d = drift(src, decl);
  if (d) throw new Error(`work/${brand}/${slug}/index.html has drifted from brands/${brand}/: ${d}\n  Re-stamp it with: node tools/new.mjs ${brand} ${slug} --revars`);

  let html = await bundleToSingleHtml(film, { runtime: 'inline', inlineColorGradingLuts: true });

  // 1. Fonts. The bundler leaves the stylesheet's url() relative; only the
  //    packager may inline them, because base64 media in the SOURCE is an
  //    upstream lint error that would skip every browser audit in gate 1.
  const faceCss = pack.face.map((f) => {
    const buf = fs.readFileSync(path.join(packDir, f.file));
    return `@font-face{font-family:'${f.family}';font-weight:${f.weight};font-style:${f.style || 'normal'};font-display:block;src:url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2')}`;
  }).join('');
  html = stripFaceRules(html);

  // 2. The chrome, and the handful of facts it needs.
  const meta = readMeta(film);
  const ms = {
    film: `${brand}-${slug}`,
    width: pack.defaults.width,
    height: pack.defaults.height,
    ...(meta.poster != null ? { poster: meta.poster } : {}),
    ...(meta.captions?.length ? { captions: meta.captions } : {}),
    ...(meta.audio ? { audio: true } : {}),
  };
  const chromeCss = fs.readFileSync(path.join(ROOT, 'lib/chrome/chrome.css'), 'utf8');
  const chromeJs = fs.readFileSync(path.join(ROOT, 'lib/chrome/chrome.js'), 'utf8');

  html = html.replace(
    /<\/head>/i,
    `<meta http-equiv="Content-Security-Policy" content="${CSP}">\n`
    + `<meta name="viewport" content="width=device-width,initial-scale=1">\n`
    + `<style>${faceCss}</style>\n<style>${chromeCss}</style>\n</head>`,
  );
  html = html.replace(
    /<\/body>/i,
    `<script>window.__ms=${jsSafe(JSON.stringify(ms))}</script>\n<script>${jsSafe(chromeJs)}</script>\n</body>`,
  );

  // 3. Attribution. Neither HyperFrames package ships a NOTICE file, so the
  //    Apache-2.0 obligation is discharged here or nowhere.
  const rtVersion = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules/@hyperframes/core/package.json'), 'utf8')).version;
  const gsapVersion = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules/gsap/package.json'), 'utf8')).version;
  html = `<!--\n  ${pack.name} — ${slug}. Generated by motion-studio; do not edit.\n\n`
    + `  Contains the HyperFrames runtime v${rtVersion}, inlined and unmodified.\n`
    + `  Copyright HeyGen, Inc. Licensed under the Apache License, Version 2.0.\n`
    + `  http://www.apache.org/licenses/LICENSE-2.0\n\n`
    + `  Contains GSAP v${gsapVersion}. Copyright Webflow, Inc. Standard license: https://gsap.com/standard-license\n`
    + `  Fonts and media: see brands/${brand}/LICENSES.json in the source repository.\n-->\n`
    + html;

  // 4. Assert the thing is actually self-contained. The regex is a cheap first
  //    pass; gate 2 is the real one, because a blocked request produces no
  //    Resource-Timing entry at all and only a live browser can see the rest.
  const bad = [];

  // Scan MARKUP, not the whole document. The inlined runtime is ~400 KB of JS
  // that legitimately contains `src="${CSS.escape(x)}"` and `new URL(...)`;
  // scanning it reports a hundred references that do not exist. Script bodies
  // are dropped and their open tags kept, so `<script src=` is still caught.
  const markup = html.replace(/<script([^>]*)>[\s\S]*?<\/script>/gi, '<script$1></script>');

  const scriptSrc = markup.match(/<script[^>]*\ssrc\s*=/gi) || [];
  if (scriptSrc.length) bad.push(`${scriptSrc.length} <script src=> remain`);
  // Anything left with a src/href that is not a data: URI or an in-document
  // anchor is a live reference. A film has no links, so there is no exception.
  for (const m of markup.matchAll(/\b(?:src|href)\s*=\s*["'](?!data:|#)([^"']*)["']/gi)) {
    bad.push(`non-inline reference: ${m[0].slice(0, 90)}`);
  }
  const css = [
    ...[...markup.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map((m) => m[1]),
    ...[...markup.matchAll(/\sstyle="([^"]*)"/gi)].map((m) => m[1]),
  ].join('\n');
  for (const m of css.matchAll(/url\(\s*(['"]?)(?!data:)([^)'"]+)\1\s*\)/gi)) {
    // `#n`, and its percent-encoded form `%23n`, are in-document SVG
    // references — what a filter or mask inside an inlined data URI looks like.
    if (!/^(?:#|%23)/.test(m[2])) bad.push(`non-inline css url(): ${m[2].slice(0, 70)}`);
  }
  if (/jsdelivr|cdn\./i.test(html)) bad.push('a cdn hostname appears in the output');
  if (bad.length) throw new Error(`the bundle is not self-contained:\n  - ${[...new Set(bad)].join('\n  - ')}`);

  const out = path.join(ROOT, 'builds', `${brand}-${slug}.html`);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, html);

  const buf = Buffer.from(html);
  const sizes = {
    raw: buf.length,
    gzip: zlib.gzipSync(buf, { level: 9 }).length,
    brotli: zlib.brotliCompressSync(buf, { params: { [zlib.constants.BROTLI_PARAM_QUALITY]: 11 } }).length,
  };
  index(brand, slug, pack, sizes, rtVersion, gsapVersion);
  return { out, sizes, faces: pack.face.length };
}

/** Drop the @font-face rules the prepared brand.css contributed; the packager
 *  replaces them with base64 equivalents. Keeps the bundle from carrying both. */
function stripFaceRules(html) {
  return html.replace(/@font-face\s*\{[^}]*\}/gi, (m) => (/url\(\s*['"]?(?!data:)/i.test(m) ? '' : m));
}

/** Optional per-film facts the chrome needs. Absent for a plain silent film. */
function readMeta(film) {
  const f = path.join(film, 'chrome.json');
  return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : {};
}

/** builds/index.json is the shipping manifest, sharded by nothing and read by
 *  the review page. Structured, sorted, so two runs produce the same bytes. */
function index(brand, slug, pack, sizes, rtVersion, gsapVersion) {
  const f = path.join(ROOT, 'builds', 'index.json');
  const j = fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : { films: {} };
  j.films[`${brand}-${slug}`] = {
    brand, slug, name: pack.name,
    file: `${brand}-${slug}.html`,
    bytes: sizes,
    pins: { hyperframes: rtVersion, gsap: gsapVersion },
  };
  const sorted = { films: {} };
  for (const k of Object.keys(j.films).sort()) sorted.films[k] = j.films[k];
  fs.writeFileSync(f, JSON.stringify(sorted, null, 2) + '\n');
}

if (process.argv[1]?.endsWith('build.mjs')) {
  const [brand, slug] = process.argv.slice(2);
  if (!brand || !slug) { console.error('usage: npm run build <brand> <slug>'); process.exit(2); }
  const r = await build(brand, slug);
  const k = (n) => (n / 1024).toFixed(1) + ' KB';
  console.log(`  built builds/${brand}-${slug}.html  raw ${k(r.sizes.raw)} · gzip ${k(r.sizes.gzip)} · brotli ${k(r.sizes.brotli)} · ${r.faces} faces inlined`);
}
