// Materialize, never reference.
//
// ../ in an authored asset path is a hard upstream lint error and a runtime 404,
// a symlink into compositions/ passes check and is then silently dropped from
// the cloud render zip, and no shipped asset may live under a dot directory.
// So sharing across projects cannot work by reference. This copies what a film
// needs into the film, deterministically, before any CLI command runs. The
// copies are gitignored build artifacts; the sources stay single-copy, so a
// shared-scene change is still one diff in one place.
import fs from 'node:fs';
import path from 'node:path';
import { emit } from './tokens.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');

export async function prepare(brand, slug, opts = {}) {
  const film = path.join(ROOT, 'work', brand, slug);
  if (!fs.existsSync(path.join(film, 'index.html'))) {
    throw new Error(`no film at work/${brand}/${slug}/index.html`);
  }
  const { pack, values } = await emit(brand);
  const packDir = path.join(ROOT, 'brands', brand);
  const shared = path.join(film, 'compositions', '_shared');
  const media = path.join(film, 'media');
  const wrote = [];

  // A stale generated tree is worse than none: a scene deleted upstream would
  // keep resolving from a leftover copy and the film would still pass.
  for (const d of [shared, media]) fs.rmSync(d, { recursive: true, force: true });
  fs.mkdirSync(shared, { recursive: true });
  fs.mkdirSync(media, { recursive: true });

  // 1. GSAP. The blank HyperFrames scaffold loads it from a CDN, which would
  //    break the zero-request invariant upstream of packaging.
  wrote.push(copy(path.join(ROOT, 'lib/vendor/gsap.min.js'), path.join(film, 'gsap.min.js')));

  // 2. Brand CSS: the resolved surfaces, plus @font-face rules pointing at the
  //    materialized files. Relative paths, never base64 — base64 media is an
  //    upstream lint error and fonts are only inlined by the packager, after
  //    gate 1 has already run.
  //    brand.css sits at the FILM ROOT, not under compositions/, so every font
  //    url is `media/x.woff2` with no `../` in it. A parent traversal in any
  //    authored asset path is a hard upstream lint error and a runtime 404.
  const faces = pack.face.map((f) => {
    const to = path.join(media, path.basename(f.file));
    copy(path.join(packDir, f.file), to);
    return `@font-face {\n  font-family: '${f.family}';\n  font-weight: ${f.weight};\n  font-style: ${f.style || 'normal'};\n  font-display: block;\n  src: url('media/${path.basename(f.file)}') format('woff2');\n}`;
  });
  const surfaces = fs.existsSync(path.join(packDir, 'surfaces.css'))
    ? fs.readFileSync(path.join(packDir, 'surfaces.css'), 'utf8')
    : '';
  fs.writeFileSync(
    path.join(film, 'brand.css'),
    `/* GENERATED by tools/prepare.mjs from brands/${brand}/. Do not edit. */\n${faces.join('\n')}\n\n${surfaces}`,
  );
  wrote.push('brand.css');

  // 3. Brand logos, as files. Shapes in gfx/ are NOT copied: an SVG loaded
  //    through src cannot read the document's custom properties, so a
  //    token-bound shape has to be inlined as markup at authoring time. The
  //    generated gfx.catalog.md is how an agent finds one without reading all.
  for (const [name, rel] of Object.entries(pack.logo || {})) {
    const from = path.join(packDir, rel);
    if (!fs.existsSync(from)) throw new Error(`brands/${brand}/brand.ts declares logo.${name} = ${rel}, which does not exist`);
    wrote.push(copy(from, path.join(media, path.basename(rel))));
  }

  // 4. Shared scenes the film asks for, by name, in its own STORYBOARD.
  //    Each shared scene is its own check-able harness project upstream, so we
  //    copy only the composition file, not the harness.
  for (const name of opts.scenes || scenesUsed(film)) {
    const from = path.join(ROOT, 'lib/scenes', name, 'compositions', name + '.html');
    if (!fs.existsSync(from)) throw new Error(`work/${brand}/${slug} references shared scene "${name}", but lib/scenes/${name}/compositions/${name}.html does not exist`);
    wrote.push(copy(from, path.join(shared, name + '.html')));
  }

  // 5. The motion sidecar, only when asked for. `check` auto-discovers any
  //    *.motion.json in the project and the audit it triggers samples ~240
  //    frames, roughly doubling a run — so the authored file is motion.spec.json
  //    and only tier 3 materializes it under the name check looks for.
  const spec = path.join(film, 'motion.spec.json');
  const live = path.join(film, 'index.motion.json');
  fs.rmSync(live, { force: true });
  if (opts.motion && fs.existsSync(spec)) {
    const j = JSON.parse(fs.readFileSync(spec, 'utf8'));
    delete j._note;
    fs.writeFileSync(live, JSON.stringify(j, null, 2) + '\n');
    wrote.push('index.motion.json');
  }

  return { film, pack, values, wrote, faces: pack.face.length };
}

/** Shared scenes are discovered from the film's own composition sources, so a
 *  film declares its dependencies by using them and nothing can drift. */
function scenesUsed(film) {
  const names = new Set();
  const files = [path.join(film, 'index.html'), ...ls(path.join(film, 'compositions')).filter((f) => f.endsWith('.html'))];
  for (const f of files) {
    if (!fs.existsSync(f)) continue;
    for (const m of fs.readFileSync(f, 'utf8').matchAll(/data-composition-src\s*=\s*["']compositions\/_shared\/([A-Za-z0-9_-]+)\.html["']/g)) {
      names.add(m[1]);
    }
  }
  return [...names];
}

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  return path.relative(ROOT, to).split(path.sep).join('/');
}
const ls = (d) => (fs.existsSync(d) ? fs.readdirSync(d).map((n) => path.join(d, n)).filter((f) => fs.statSync(f).isFile()) : []);

if (process.argv[1]?.endsWith('prepare.mjs')) {
  const [brand, slug, ...flags] = process.argv.slice(2);
  if (!brand || !slug) { console.error('usage: npm run pre <brand> <slug> [--motion]'); process.exit(2); }
  const r = await prepare(brand, slug, { motion: flags.includes('--motion') });
  console.log(`  prepared work/${brand}/${slug}: ${r.faces} face(s), ${r.wrote.length} file(s) materialized`);
}
